"""initial schema

Revision ID: c2cbbaf0747d
Revises:
Create Date: 2025-11-09 12:42:37.964318

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c2cbbaf0747d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaign_results",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("campaign_id", sa.String(), nullable=False),
        sa.Column("store_id", sa.String(), nullable=False),
        sa.Column("conversion_rate", sa.Float(), nullable=True),
        sa.Column(
            "send_status", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_campaign_results_campaign_id",
        "campaign_results",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        "idx_campaign_results_store_campaign",
        "campaign_results",
        ["store_id", "campaign_id"],
        unique=False,
    )
    op.create_index(
        "idx_campaign_results_store_id", "campaign_results", ["store_id"], unique=False
    )
    op.create_index(
        "idx_campaign_results_timestamp",
        "campaign_results",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaign_results_campaign_id"),
        "campaign_results",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaign_results_id"), "campaign_results", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_results_store_id"),
        "campaign_results",
        ["store_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaign_results_timestamp"),
        "campaign_results",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "campaigns",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("campaign_id", sa.String(), nullable=False),
        sa.Column("store_id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("targeting", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_campaigns_campaign_id", "campaigns", ["campaign_id"], unique=False
    )
    op.create_index(
        "idx_campaigns_created_at", "campaigns", ["created_at"], unique=False
    )
    op.create_index(
        "idx_campaigns_store_campaign",
        "campaigns",
        ["store_id", "campaign_id"],
        unique=False,
    )
    op.create_index("idx_campaigns_store_id", "campaigns", ["store_id"], unique=False)
    op.create_index(
        op.f("ix_campaigns_campaign_id"), "campaigns", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_campaigns_created_at"), "campaigns", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_campaigns_id"), "campaigns", ["id"], unique=False)
    op.create_index(op.f("ix_campaigns_status"), "campaigns", ["status"], unique=False)
    op.create_index(
        op.f("ix_campaigns_store_id"), "campaigns", ["store_id"], unique=False
    )
    op.create_index(op.f("ix_campaigns_type"), "campaigns", ["type"], unique=False)
    op.create_table(
        "chat_session_states",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.String(), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_chat_session_states_session_id",
        "chat_session_states",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        "idx_chat_session_states_store_id",
        "chat_session_states",
        ["store_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_session_states_session_id"),
        "chat_session_states",
        ["session_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_chat_session_states_store_id"),
        "chat_session_states",
        ["store_id"],
        unique=False,
    )
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_chat_sessions_active", "chat_sessions", ["is_active"], unique=False
    )
    op.create_index(
        "idx_chat_sessions_store_active",
        "chat_sessions",
        ["store_id", "is_active"],
        unique=False,
    )
    op.create_index(
        "idx_chat_sessions_store_id", "chat_sessions", ["store_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_sessions_is_active"), "chat_sessions", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_chat_sessions_store_id"), "chat_sessions", ["store_id"], unique=False
    )
    op.create_table(
        "consumers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("store_id", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("number_of_orders", sa.Integer(), nullable=True),
        sa.Column("last_order_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_consumers_last_order", "consumers", ["last_order_date"], unique=False
    )
    op.create_index("idx_consumers_phone", "consumers", ["phone"], unique=False)
    op.create_index("idx_consumers_store_id", "consumers", ["store_id"], unique=False)
    op.create_index(
        "idx_consumers_store_phone", "consumers", ["store_id", "phone"], unique=False
    )
    op.create_index(op.f("ix_consumers_id"), "consumers", ["id"], unique=False)
    op.create_index(
        op.f("ix_consumers_last_order_date"),
        "consumers",
        ["last_order_date"],
        unique=False,
    )
    op.create_index(op.f("ix_consumers_phone"), "consumers", ["phone"], unique=False)
    op.create_index(
        op.f("ix_consumers_store_id"), "consumers", ["store_id"], unique=False
    )
    op.create_table(
        "feedbacks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("store_id", sa.String(), nullable=False),
        sa.Column("store_consumer_id", sa.String(), nullable=True),
        sa.Column("order_id", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_feedbacks_category", "feedbacks", ["category"], unique=False)
    op.create_index(
        "idx_feedbacks_created_at", "feedbacks", ["created_at"], unique=False
    )
    op.create_index("idx_feedbacks_order_id", "feedbacks", ["order_id"], unique=False)
    op.create_index(
        "idx_feedbacks_store_created",
        "feedbacks",
        ["store_id", "created_at"],
        unique=False,
    )
    op.create_index("idx_feedbacks_store_id", "feedbacks", ["store_id"], unique=False)
    op.create_index(
        op.f("ix_feedbacks_category"), "feedbacks", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_feedbacks_created_at"), "feedbacks", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_feedbacks_id"), "feedbacks", ["id"], unique=False)
    op.create_index(
        op.f("ix_feedbacks_order_id"), "feedbacks", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_feedbacks_store_consumer_id"),
        "feedbacks",
        ["store_consumer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_feedbacks_store_id"), "feedbacks", ["store_id"], unique=False
    )
    op.create_table(
        "menu_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("store_id", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("device_type", sa.String(), nullable=True),
        sa.Column("platform", sa.String(), nullable=True),
        sa.Column(
            "event_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_menu_events_event_type", "menu_events", ["event_type"], unique=False
    )
    op.create_index(
        "idx_menu_events_session_id", "menu_events", ["session_id"], unique=False
    )
    op.create_index(
        "idx_menu_events_store_event",
        "menu_events",
        ["store_id", "event_type"],
        unique=False,
    )
    op.create_index(
        "idx_menu_events_store_id", "menu_events", ["store_id"], unique=False
    )
    op.create_index(
        "idx_menu_events_store_timestamp",
        "menu_events",
        ["store_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_menu_events_timestamp", "menu_events", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_menu_events_event_type"), "menu_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_menu_events_id"), "menu_events", ["id"], unique=False)
    op.create_index(
        op.f("ix_menu_events_session_id"), "menu_events", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_menu_events_store_id"), "menu_events", ["store_id"], unique=False
    )
    op.create_index(
        op.f("ix_menu_events_timestamp"), "menu_events", ["timestamp"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("store_id", sa.String(), nullable=False),
        sa.Column("total_price", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("products", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_orders_created_at", "orders", ["created_at"], unique=False)
    op.create_index(
        "idx_orders_store_created", "orders", ["store_id", "created_at"], unique=False
    )
    op.create_index("idx_orders_store_id", "orders", ["store_id"], unique=False)
    op.create_index(op.f("ix_orders_code"), "orders", ["code"], unique=False)
    op.create_index(
        op.f("ix_orders_created_at"), "orders", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    op.create_index(op.f("ix_orders_store_id"), "orders", ["store_id"], unique=False)
    op.create_index(op.f("ix_orders_uuid"), "orders", ["uuid"], unique=True)
    op.create_table(
        "stores",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("cnpj", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_stores_id", "stores", ["id"], unique=False)
    op.create_index("idx_stores_uuid", "stores", ["uuid"], unique=False)
    op.create_index(op.f("ix_stores_cnpj"), "stores", ["cnpj"], unique=False)
    op.create_index(op.f("ix_stores_id"), "stores", ["id"], unique=False)
    op.create_index(op.f("ix_stores_uuid"), "stores", ["uuid"], unique=True)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_chat_messages_created_at", "chat_messages", ["created_at"], unique=False
    )
    op.create_index(
        "idx_chat_messages_session_id", "chat_messages", ["session_id"], unique=False
    )
    op.create_index(
        "idx_chat_messages_store_id", "chat_messages", ["store_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_messages_created_at"),
        "chat_messages",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_messages_session_id"),
        "chat_messages",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_messages_store_id"), "chat_messages", ["store_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_messages_store_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_session_id"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_created_at"), table_name="chat_messages")
    op.drop_index("idx_chat_messages_store_id", table_name="chat_messages")
    op.drop_index("idx_chat_messages_session_id", table_name="chat_messages")
    op.drop_index("idx_chat_messages_created_at", table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_stores_uuid"), table_name="stores")
    op.drop_index(op.f("ix_stores_id"), table_name="stores")
    op.drop_index(op.f("ix_stores_cnpj"), table_name="stores")
    op.drop_index("idx_stores_uuid", table_name="stores")
    op.drop_index("idx_stores_id", table_name="stores")
    op.drop_table("stores")
    op.drop_index(op.f("ix_orders_uuid"), table_name="orders")
    op.drop_index(op.f("ix_orders_store_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_created_at"), table_name="orders")
    op.drop_index(op.f("ix_orders_code"), table_name="orders")
    op.drop_index("idx_orders_store_id", table_name="orders")
    op.drop_index("idx_orders_store_created", table_name="orders")
    op.drop_index("idx_orders_created_at", table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_menu_events_timestamp"), table_name="menu_events")
    op.drop_index(op.f("ix_menu_events_store_id"), table_name="menu_events")
    op.drop_index(op.f("ix_menu_events_session_id"), table_name="menu_events")
    op.drop_index(op.f("ix_menu_events_id"), table_name="menu_events")
    op.drop_index(op.f("ix_menu_events_event_type"), table_name="menu_events")
    op.drop_index("idx_menu_events_timestamp", table_name="menu_events")
    op.drop_index("idx_menu_events_store_timestamp", table_name="menu_events")
    op.drop_index("idx_menu_events_store_id", table_name="menu_events")
    op.drop_index("idx_menu_events_store_event", table_name="menu_events")
    op.drop_index("idx_menu_events_session_id", table_name="menu_events")
    op.drop_index("idx_menu_events_event_type", table_name="menu_events")
    op.drop_table("menu_events")
    op.drop_index(op.f("ix_feedbacks_store_id"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_store_consumer_id"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_order_id"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_id"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_created_at"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_category"), table_name="feedbacks")
    op.drop_index("idx_feedbacks_store_id", table_name="feedbacks")
    op.drop_index("idx_feedbacks_store_created", table_name="feedbacks")
    op.drop_index("idx_feedbacks_order_id", table_name="feedbacks")
    op.drop_index("idx_feedbacks_created_at", table_name="feedbacks")
    op.drop_index("idx_feedbacks_category", table_name="feedbacks")
    op.drop_table("feedbacks")
    op.drop_index(op.f("ix_consumers_store_id"), table_name="consumers")
    op.drop_index(op.f("ix_consumers_phone"), table_name="consumers")
    op.drop_index(op.f("ix_consumers_last_order_date"), table_name="consumers")
    op.drop_index(op.f("ix_consumers_id"), table_name="consumers")
    op.drop_index("idx_consumers_store_phone", table_name="consumers")
    op.drop_index("idx_consumers_store_id", table_name="consumers")
    op.drop_index("idx_consumers_phone", table_name="consumers")
    op.drop_index("idx_consumers_last_order", table_name="consumers")
    op.drop_table("consumers")
    op.drop_index(op.f("ix_chat_sessions_store_id"), table_name="chat_sessions")
    op.drop_index(op.f("ix_chat_sessions_is_active"), table_name="chat_sessions")
    op.drop_index("idx_chat_sessions_store_id", table_name="chat_sessions")
    op.drop_index("idx_chat_sessions_store_active", table_name="chat_sessions")
    op.drop_index("idx_chat_sessions_active", table_name="chat_sessions")
    op.drop_table("chat_sessions")
    op.drop_index(
        op.f("ix_chat_session_states_store_id"), table_name="chat_session_states"
    )
    op.drop_index(
        op.f("ix_chat_session_states_session_id"), table_name="chat_session_states"
    )
    op.drop_index("idx_chat_session_states_store_id", table_name="chat_session_states")
    op.drop_index(
        "idx_chat_session_states_session_id", table_name="chat_session_states"
    )
    op.drop_table("chat_session_states")
    op.drop_index(op.f("ix_campaigns_type"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_store_id"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_status"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_id"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_created_at"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_campaign_id"), table_name="campaigns")
    op.drop_index("idx_campaigns_store_id", table_name="campaigns")
    op.drop_index("idx_campaigns_store_campaign", table_name="campaigns")
    op.drop_index("idx_campaigns_created_at", table_name="campaigns")
    op.drop_index("idx_campaigns_campaign_id", table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index(op.f("ix_campaign_results_timestamp"), table_name="campaign_results")
    op.drop_index(op.f("ix_campaign_results_store_id"), table_name="campaign_results")
    op.drop_index(op.f("ix_campaign_results_id"), table_name="campaign_results")
    op.drop_index(
        op.f("ix_campaign_results_campaign_id"), table_name="campaign_results"
    )
    op.drop_index("idx_campaign_results_timestamp", table_name="campaign_results")
    op.drop_index("idx_campaign_results_store_id", table_name="campaign_results")
    op.drop_index("idx_campaign_results_store_campaign", table_name="campaign_results")
    op.drop_index("idx_campaign_results_campaign_id", table_name="campaign_results")
    op.drop_table("campaign_results")
    # ### end Alembic commands ###
